/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RulesLazyImport = createFileRoute('/rules')()
const PlayLazyImport = createFileRoute('/play')()
const IndexLazyImport = createFileRoute('/')()
const PlayClassicLazyImport = createFileRoute('/play/classic')()

// Create/Update Routes

const RulesLazyRoute = RulesLazyImport.update({
  path: '/rules',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rules.lazy').then((d) => d.Route))

const PlayLazyRoute = PlayLazyImport.update({
  path: '/play',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/play.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PlayClassicLazyRoute = PlayClassicLazyImport.update({
  path: '/play/classic',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/play_.classic.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/play': {
      preLoaderRoute: typeof PlayLazyImport
      parentRoute: typeof rootRoute
    }
    '/rules': {
      preLoaderRoute: typeof RulesLazyImport
      parentRoute: typeof rootRoute
    }
    '/play/classic': {
      preLoaderRoute: typeof PlayClassicLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PlayLazyRoute,
  RulesLazyRoute,
  PlayClassicLazyRoute,
])

/* prettier-ignore-end */
